OpenMDM/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib import admin
import public_gate.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^public_gate/', include(public_gate.urls, namespace='public_gate')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*', RedirectView.as_view(url='/public_gate/home')),
)

public_gate/urls.py
from django.conf.urls import patterns, url
from public_gate import views

urlpatterns = patterns('',
    # Base
    url(r'^home',                                           'public_gate.views.home',                       name="home"),
    url(r'^about/$',                                        'public_gate.views.about',                      name="about"),
    url(r'^contact/$',                                      'public_gate.views.contact',                    name="contact"),

    # Authentication
    url(r'^login/$',                                        'public_gate.views.site_login',                 name="site_login"),
    url(r'^logout/$',                                       'public_gate.views.site_logout',                name="site_logout"),

    # Property lists
    url(r'^property_list/$',                                  'public_gate.views.property_lists',             name="property_lists"),
    url(r'^property_list/(?P<plist_id>[a-z0-9]{24})/$',              views.property_list_detail,                     name='property_list_detail'),
    url(r'^property_list/(?P<plist_id>[a-z0-9]{24})/download/$',     views.property_list_download,                   name='property_list_download'),
    url(r'^user/property_lists/$',                          'public_gate.views.property_lists_for_user',    name='property_lists_for_user'),
    url(r'^property_list/add/$',                            'public_gate.views.add_property_list',          name="property_list_add"),
)

public_gate/models.py
import os
import plistlib
from plistlib import dumps
import uuid
import re

from django.contrib.auth.models import User
from mongoengine import *
from common.local.settings import CONFIG
from common.utils.Utils import str_to_bool


class CustomPlist(DynamicEmbeddedDocument):
    PayloadUUID = StringField(max_length=100)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.PayloadUUID = str(uuid.uuid1()).upper()


class Plist(EmbeddedDocument):
    PayloadDisplayName = StringField(max_length=100)
    PayloadDescription = StringField(max_length=100)
    PayloadIdentifier = StringField(max_length=100)
    PayloadOrganization = StringField(max_length=100)
    PayloadRemovalDisallowed = BooleanField(default=True)
    PayloadType = StringField(max_length=100)
    PayloadUUID = StringField(max_length=100)
    PayloadVersion = IntField()
    PayloadContent = ListField(EmbeddedDocumentField(CustomPlist))

    def __init__(self, recipe=None, *args, **kwargs):
        super().__init__(*args, **kwargs) # 103 128 159
        if recipe is not None:
            self.PayloadDisplayName = recipe.get('PayloadDisplayName', '<no name>')
            self.PayloadDescription = recipe.get('PayloadDescription', '<no description>')
            self.PayloadIdentifier = recipe.get('PayloadIdentifier', '<no identifier>')
            self.PayloadOrganization = recipe.get('PayloadOrganization', '<no organization>')
            self.PayloadRemovalDisallowed = recipe.get('PayloadRemovalDisallowed', False)
            self.PayloadType = 'Configuration'
            self.PayloadUUID = str(uuid.uuid1()).upper()
            self.PayloadVersion = int(recipe.get('PayloadVersion', '1'))


class Recipe(Document):
    group_name = StringField(max_length=100)
    plist = EmbeddedDocumentField(Plist)

    def generate(self):
        """
        Generate an plist file from a PropertyList object
        """
        recipe = self.to_mongo().to_dict()
        plist = recipe['plist']

        return dumps(plist)


class RecipeForm():
    base_recipe_dict = None
    recipe_dict = None
    recipe_name = None

    def __init__(self, recipe_name=None, data=None):
        self.recipe_name = recipe_name
        self.plist = Plist()
        self.recipe = Recipe()
        self.outputs = {}
        self.base_recipe_dict = RecipeForm.get_dict_from_recipe_name("base.xml")
        self.recipe_dict = RecipeForm.get_dict_from_recipe_name(self.recipe_name)
        self.plist = Plist(self.recipe_dict)
        # If form is filled out
        if data is not None:
            self.outputs = self.parse_for_output(self.base_recipe_dict, {})
            self.outputs = self.parse_for_output(self.recipe_dict, self.outputs)
            custom_plist = CustomPlist()
            # We parse the expected outputs from the recipe
            dict_iterate = dict(self.base_recipe_dict['outputs'], **self.recipe_dict['outputs'])
            for key, value in dict_iterate.items():
                setattr(custom_plist, key, self.get_value_from_post_data(value, data))

            # Then we add recipe information
            self.plist.PayloadContent.append(custom_plist)
            self.plist.PayloadRemovalDisallowed = str_to_bool(data.get("PayloadRemovalDisallowed", False))
            self.recipe.group_name = data.get("group_id")
            self.recipe.plist = self.plist

    def save(self):
        self.recipe.save()

    @staticmethod
    def get_dict_from_recipe_name(recipe_name):
        recipes_directory = os.path.normpath(os.path.dirname(__file__) + "/../recipe/") + "/"

        # We get the required recipe
        recipe_path = recipes_directory + recipe_name

        # We get is as dict
        recipe_dict = plistlib.load(open(recipe_path, 'rb'), fmt=plistlib.FMT_XML)

        return recipe_dict

    def get_value_from_post_data(self, value, data):
        # $key?(yes):(no)
        match = re.search("^\$(.*)\?\((.*)\):\((.*)\)$", value)
        if match:
            values = dict(key=match.group(1),
                          yes=match.group(2),
                          no=match.groups(3))
            if values['key'] in data:
                return self.get_value_from_post_data(values['yes'], data)
            else:
                return self.get_value_from_post_data(values['no'], data)

        # $key?(yes):
        match = re.search("^\$(.*)\?\((.*)\):$", value)
        if match:
            values = dict(key=match.group(1),
                          yes=match.group(2))
            if values['key'] in data:
                return self.get_value_from_post_data(values['yes'], data)
            return None

        # $key?:(no)
        match = re.search("^\$(.*)\?:\((.*)\)$", value)
        if match:
            values = dict(key=match.group(1),
                          no=match.group(2))
            if values['key'] not in data:
                return self.get_value_from_post_data(values['no'], data)
            return None

        # $key?
        match = re.search("^\$(.*)\?$", value)
        if match:
            values = dict(key=match.group(1))
            if values['key'] in data:
                return self.get_value_from_post_data("$" + values['key'], data)
            return None

        # $key
        match = re.search("^\$(.*)", value)
        if match:
            values = dict(key=match.group(1))
            if values['key'] in data:
                data_type = self.outputs[values['key']]['input_type']
                if data_type == "boolean":
                    return str_to_bool(data[values['key']])
                elif data_type == "integer":
                    return int(data[values['key']])
                else:
                    return data[values['key']]
            return None

        # @UUID
        match = re.search("^@UUID$", value)
        if match:
            return str(uuid.uuid1()).upper()

        # @constant
        match = re.search("^@(.*)", value)
        if match:
            if match.group(1) in ("YES", "NO"):
                return bool(match.group(1))
            return match.group(1)

    @staticmethod
    def display_input(input_type, key, required, values, default_value, saved_value):
        """
        Creates HTML input, depending of the entry type
        :param input_type:
        :param key:
        :param required:
        :param values:
        :param default_value:
        :return string:
        """
        current_input = '<input type="{type}" ' \
                        'class="{input_class}" ' \
                        'name="{name}"' \
                        '{required}' \
                        '{checked} ' \
                        'value="{value}" ' \
                        'id="{id}">'
        if input_type == "string":
            current_input = current_input.format(id=key,
                                                 type="text",
                                                 input_class="form-control",
                                                 name=key,
                                                 required=" required" if required else "",
                                                 checked="",
                                                 value=saved_value if saved_value is not None
                                                 else default_value if default_value is not None
                                                 else "")
        elif input_type == "boolean":
            # Hack for posting checkbox even if it's unchecked. Hidden input value will be used in case of
            # the checkbox is unchecked

            hidden_input = '<input type="hidden" ' \
                           'name="{name}"' \
                           'value="{value}">'.format(name=key,
                                                     value="False")

            current_input = hidden_input + current_input.format(id=key,
                                                                type="checkbox",
                                                                input_class="",
                                                                name=key,
                                                                required="",
                                                                checked=" checked" if saved_value is not None and saved_value
                                                                else "" if saved_value is not None and not saved_value
                                                                else " checked" if default_value
                                                                else "",
                                                                value="True")
        elif input_type == "integer":
            current_input = current_input.format(id=key,
                                                 type="number",
                                                 input_class="form-control",
                                                 name=key,
                                                 required=" required" if required else "",
                                                 checked="",
                                                 value=saved_value if saved_value is not None
                                                 else default_value if default_value is not None
                                                 else "")
        elif input_type == "list":
            select = ['<select class="form-control" name="{name}"{required} id="{id}">'.format(name=key,
                                                                                               required=" required"
                                                                                               if required
                                                                                               else "",

public_gate/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.core import serializers
from OpenMDM import settings
import os
from public_gate.models import RecipeForm, Recipe


def home(request):
    """
    Displays home page
    :param request:
    :return render:
    """
    d = {}
    return render(request, 'public_gate/home.html', d)


def about(request):
    """
    Displays about page
    :param request:
    :return render:
    """
    d = {}
    return render(request, 'public_gate/about.html', d)


def contact(request):
    """
    Displays contact page
    :param request:
    :return render:
    """
    d = {}
    return render(request, 'public_gate/contact.html', d)


########################################################################
#                                                                      #
#                       Authentication Views
#                                                                      #
########################################################################


def site_login(request):
    """
    Logs in current user
    :param request:
    :return render:
    """
    if request.method == "POST":
        user = None
        user_login = request.POST['login']
        user_password = request.POST['password']
        print("Login tryout by "+user_login)
        if user_login != "" and user_password != "":
            user = authenticate(username=user_login, password=user_password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('public_gate:home'))
        else:
            # User.objects.create_user(user_login, '', user_password).save()
            return render(request, 'public_gate/home.html', {"error_message": "Wrong login/password combination"})
    return render(request, 'public_gate/home.html', {"error_message": "One or more fields are empty"})


def site_logout(request):
    """
    Logs out current user
    :param request:
    :return render:
    """
    logout(request)
    return HttpResponseRedirect(reverse('public_gate:home'))


########################################################################
#                                                                      #
#                       Property List Views
#                                                                      #
########################################################################


def property_lists(request):
    """
    Fetches all property lists
    From: property_list/
    :param request: 
    :return render:
    """
    property_lists = Recipe.objects.all()
    return render(request, 'public_gate/property_lists.html', dict(property_lists=dict(all=property_lists)))


def property_lists_for_user(request):
    """
    Fetches plists for specific user
    From: user/<user_id>/property_list/
    :param request:
    :param user_id:
    :return render:
    """
    property_lists = {}
    if settings.RETRIEVE_PLIST_FROM_GROUPS == "all":
        groups = request.user.ldap_user.group_names
    else:
        groups = {request.user.ldap_user.attrs['gidnumber'][0]}
    for group in groups:
        plists = Recipe.objects(group_name=group)
        if len(plists) > 0:
            for plist in plists:
                plist.id = str(plist.id)
            property_lists[group] = Recipe.objects(group_name=group)

    return render(request, 'public_gate/property_lists.html', dict(property_lists=property_lists))


def property_list_detail(request, plist_id):
    """
    Fetches one plist
    From: property_list/<plist_id>/
    :param request: 
    :param plist_id: 
    :return render:
    """

    plist = Recipe.objects(id=plist_id)
    return render(request, 'public_gate/property_list_detail.html', dict(plist=plist[0]))


def property_list_download(request, plist_id):
    """
    Fetches one plist and converts it to plist format (xml based)
    From: property_list/<plist_id>/download/
    :param request: 
    :param plist_id: 
    :return:
    """
    plist = Recipe.objects(id=plist_id)
    plist = plist[0].generate()
    response = render(request, 'public_gate/property_list_download.html', dict(plist=plist), content_type="application/x-apple-aspen-config")
    response['Content-Disposition'] = "attachment; filename={plist_id}.mobileconfig".format(plist_id=plist_id)
    return response


def add_property_list(request):
    """
    Adds one property list
    From: property_list/add/
    :param request:
    :return:
    """
    form = False
    files = False
    if request.method == 'POST' and "file" in request.POST:
        form = RecipeForm(request.POST.get('file')).html_output()
    else:
        if request.method == 'POST':
            # We save the plist
            file_name = request.POST.get('recipe_file')
            form = RecipeForm(recipe_name=file_name,
                              data=request.POST)
            form.save()
            form = False

        # We display all the recipes available
        files = []
        for file in os.listdir(os.path.dirname(__file__) + "/../recipe"):
            if file.endswith(".plist"):
                files.append(file)
    return render(request, 'public_gate/property_list_add.html', dict(files=files,
                                                                      form=form))

templates/public_gate/about.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <p>
            Test de about
        </p>
    </div>
</div>
{% endblock %}

templates/public_gate/contact.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
    <form class="form-horizontal" style="width:50%;">
        <fieldset>

            <!-- Form Name -->
            <legend>Contact</legend>

            <!-- Text input-->
            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control" id="email" name="email" placeholder="email" required="" type="text">

            </div>

            <!-- Textarea -->
            <div class="form-group">
                <label for="message">Message</label>
                <textarea class="form-control" id="message" name="message">Your message</textarea>
            </div>

            <!-- Button -->
            <div class="form-group">
                <label for="send"></label>
                <button id="send" name="send" class="btn btn-success">Send</button>
            </div>

        </fieldset>
    </form>
</div>

{% endblock %}

templates/public_gate/home.html
{% extends "base_template.html" %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>OpenMDM Project</h1>
        <p>
            This Mobile Device Management platform is open-source and awesome. Check it out !
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        {% if not user.is_authenticated %}
            <h2>You must be logged in</h2>
        {% else %}
            <h2>Welcome {{ user.username }}</h2>
            <a class="btn btn-success btn-lg" href="{% url 'public_gate:property_lists_for_user' %}" >Your property lists &raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/public_gate/property_list_add.html
{% extends "base_template.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
    <div class="row">
        <h2>Add a Property list</h2>
        <form action="{% url 'public_gate:property_list_add' %}" method="post">
            {% csrf_token %}
            {% if not form %}
                <div class="form-group">
                    <select class="form-control" name="file">
                        {% for file in files %}
                            <option value="{{ file }}">{{ file }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-group-lg btn-success" type="submit" value="select_recipe">Select recipe</button>

            {% else %}
                <form action="{% url 'public_gate:property_list_add' %}" method="post">
                    {% csrf_token %}
                    {{ form | safe }}
                    <button class="btn btn-group-lg btn-success" type="submit" value="Add plist">Add plist</button>
                </form>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

templates/public_gate/property_list_detail.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>{{ plist.plist.PayloadContent.0.PayloadDisplayName }} (ID : {{ plist.id }}) <a class="btn btn-primary btn-lg" href="{% url 'public_gate:property_list_download' plist.id %}"  >Download &raquo;</a></h2>
            <div>
                <h3>
                    Property List description
                </h3>
                <p>
                    {{ plist.plist.PayloadContent.0.PayloadDescription }}
                </p>
                <h3>
                    Recipe characteristics
                </h3>
                <table class="table table-striped table-condensed">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                {% load app_filters %}
                {% for key in plist.plist %}
                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ plist.plist|get_item:key }}</td>
                    </tr>
                {% endfor %}
                </table>
                <h3>
                    Property List characteristics
                </h3>
                <table class="table table-striped table-condensed">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                {% load app_filters %}
                {% for key in plist.plist.PayloadContent.0 %}
                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ plist.plist.PayloadContent.0|get_item:key }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
    </div>
</div>
{% endblock %}

templates/public_gate/property_list_download.html
{{ plist | safe }}

templates/public_gate/property_lists.html
{% extends "base_template.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Property Lists{% if 'admin' in user.ldap_user.group_names %} <a class="btn btn-success" href="{% url 'public_gate:property_list_add' %}" >+ Add plist</a>{% endif %}</h2>

        <table class="table table-striped">
            <tr>
                <th>Group</th>
                <th>Name</th>
                <th>Download</th>
            </tr>
            {% for group, plists in property_lists.items %}
                {% for plist in plists %}
                    <tr>
                        <td>{{ plist.group_name }}</td>
                        <td><a href="{% url 'public_gate:property_list_detail' plist.id %}">{{ plist.plist.PayloadContent.0.PayloadDisplayName }}</a></td>
                        <td><a class="btn btn-primary" href="{% url 'public_gate:property_list_download' plist.id %}" >Download &raquo;</a></td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}