OpenMDM/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib import admin
import public_gate.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^public_gate/', include(public_gate.urls, namespace='public_gate')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*', RedirectView.as_view(url='/public_gate/home')),
)

public_gate/urls.py
from django.conf.urls import patterns, url
from public_gate import views

urlpatterns = patterns('',
    # Base
    url(r'^home',                                           'public_gate.views.home',                       name="home"),
    url(r'^about/$',                                        'public_gate.views.about',                      name="about"),
    url(r'^contact/$',                                      'public_gate.views.contact',                    name="contact"),

    # Authentication
    url(r'^login/$',                                        'public_gate.views.site_login',                 name="site_login"),
    url(r'^logout/$',                                       'public_gate.views.site_logout',                name="site_logout"),

    # Property lists
    url(r'^property_list/$',                                  'public_gate.views.property_lists',             name="property_lists"),
    url(r'^property_list/(?P<plist_id>[a-z0-9]{24})/$',              views.property_list_detail,                     name='property_list_detail'),
    url(r'^property_list/(?P<plist_id>[a-z0-9]{24})/download/$',     views.property_list_download,                   name='property_list_download'),
    url(r'^user/property_lists/$',                          'public_gate.views.property_lists_for_user',    name='property_lists_for_user'),
    url(r'^property_list/add/$',                            'public_gate.views.add_property_list',          name="property_list_add"),
)

templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Betezed">
    <!-- <link rel="shortcut icon" href="/static/img/favicon.png"> -->

    <title>OpenMDM Gateway</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <style type="text/css">
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
        padding-top: 50px;
        padding-bottom: 20px;
        }
    </style>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/static/js/html5shiv.js"></script>
    <script src="/static/js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'public_gate:home' %}">OpenMDM</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'public_gate:home' %}">Home</a></li>
                {% if 'admin' in user.ldap_user.group_names %}
                    <li><a href="{% url 'public_gate:property_lists' %}">plists</a></li>
                {% endif %}
                <li><a href="{% url 'public_gate:contact' %}">Contact</a></li>
                <li><a href="{% url 'public_gate:about' %}">About</a></li>
                {% if False %}
                    <li><a href="{% url 'admin:index' %}">Admin panel</a></li>
                {% endif %}
            </ul>
            {% if not user.is_authenticated %}
                <form class="navbar-form navbar-right" action="{% url 'public_gate:site_login' %}" method="post">
                    {% csrf_token %}
                    {% if error_message %}
                    <div class="form-group has-error">
                        <label class="control-label">{{ error_message }}</label>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <input type="text" placeholder="Login" class="form-control" name="login">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" class="form-control" name="password">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">{{ user.username }}</a></li>
                    <li><a href="{% url 'public_gate:site_logout' %}">Logout</a></li>
                </ul>
            {% endif %}
        </div><!--/.navbar-collapse -->
    </div>
</div>

<!-- Main jumbotron for a primary marketing message or call to action -->


{% block content %}
{% endblock %}
<div class="container">

<hr>
<footer>
    <p>&copy; OpenMDM Project 2015</p>
</footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>